/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package word.count;

import java.io.IOException;
import java.util.Map;

public class App {
    public static void main(String[] args) throws IOException {
        WordCountWordBoundary wordCount = new WordCountWordBoundary();

        String file = "src/main/resources/shakespeare.txt";

        Map<String, Long> wordCountMap = wordCount.wordCharacterRegex(file);

        wordCountMap.forEach((k,v) -> System.out.printf("%s -> %s %n", k, v));


    }
}
